version: '3.8'

services:
  streamlit:
    build: .
    command: streamlit run dashboards/control_center.py
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    restart: always

  fastapi:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always

  scheduler:
    build: .
    command: python3 runloop.py
    volumes:
      - .:/app
    restart: always